---
- name: Test Dynatrace Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Debug Event
      condition: event is defined
      action:
        debug:
          msg: "Received Dynatrace alert: {{ event }}"

