---
- name: Execute command in WebSphere Liberty pod
  hosts: localhost
  tasks:
    - name: Find WebSphere Liberty pod
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default  # replace with your namespace
        label_selectors:
          app: websphere-liberty  # replace with the label of your WebSphere pod
      register: websphere_pod

    - name: Exec into the WebSphere Liberty pod
      kubernetes.core.k8s_exec:
        pod: "{{ websphere_pod.resources[0].metadata.name }}"
        namespace: default  # replace with your namespace
        cmd: ["/bin/sh", "-c", "your-command-here"]  # replace with the actual command you want to run
      when: websphere_pod.resources | length > 0
