- name: Restart WebSphere Application Server on Windows
  hosts: websphere_servers
  gather_facts: false
  tasks:
    - name: Stop WebSphere Server
      ansible.windows.win_shell: |
        cd "C:\IBM\WebSphere\AppServer\bin"
        .\stopServer.bat server1 -username admin -password pass
      args:
        chdir: 'C:\IBM\WebSphere\AppServer\bin'
      register: stop_output
      ignore_errors: true

    - name: Wait for WebSphere to stop completely
      pause:
        seconds: 10

    - name: Start WebSphere Server
      ansible.windows.win_shell: |
        cd "C:\IBM\WebSphere\AppServer\bin"
        .\startServer.bat server1
      args:
        chdir: 'C:\IBM\WebSphere\AppServer\bin'
      register: start_output

    - name: Display WebSphere start output
      debug:
        var: start_output.stdout
