---
- name: Debug WebSphere Liberty restart in pod
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Find WebSphere Liberty pod
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: websphere-liberty  # Replace with your namespace
      register: websphere_pod

    - name: Debug the pod info
      debug:
        var: websphere_pod

    - name: Restart WebSphere Liberty server in the pod
      kubernetes.core.k8s_exec:
        pod: "{{ websphere_pod.resources[0].metadata.name }}"
        namespace: websphere-liberty  # Replace with your namespace
        command:
          - /bin/sh
          - -c
          - /opt/ibm/wlp/bin/server stop defaultServer && /opt/ibm/wlp/bin/server start defaultServer
      when: websphere_pod.resources | length > 0
