- name: Restart WebSphere Liberty inside pod
  hosts: websphere
  gather_facts: false
  tasks:
    - name: Find WebSphere Liberty pod
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: websphere-liberty
        label_selectors:
          - app=websphere-liberty
      register: pods

    - name: Restart WebSphere Liberty inside pod
      kubernetes.core.k8s_exec:
        namespace: websphere-liberty
        pod: "{{ pods.resources[0].metadata.name }}"
        command:
          - /bin/bash
          - -c
          - >
            /opt/ibm/wlp/bin/server stop defaultServer && sleep 3 && /opt/ibm/wlp/bin/server start defaultServer
